### ISSUE TITLE
what's your meaning of feedback of chatbot?

### ISSUE THREAD

**Issue by NonvolatileMemory** [Larryjianfeng/NLP-#2]
I am working on a paper about use feedback to improve the performance of chatbots!
but my data should be collect by human and it's very expensive
so I want to know more details about your data collection, very thanks!

**Comment by Larryjianfeng** [comment]
When I was working on the chatbot at IQIYI, when there was a question to the chatbot, it would give some optional choices for the user to decide which one was the best. The choice could be used as training data.
